# Generated by Django 4.2.23 on 2025-08-07 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        100.0, message="Percentage cannot exceed 100."
                    ),
                    django.core.validators.MinValueValidator(
                        0.0, message="Percentage cannot be negative."
                    ),
                ],
            ),
        ),
    ]
